In [45]:
import numpy as np

In [46]:
from numpy import genfromtxt
my_data = genfromtxt('p107_network.txt', delimiter=',')

In [41]:
np.nansum(my_data)

523664.0

In [47]:
where_nan = np.isnan(my_data)

In [48]:
my_data[where_nan] = np.inf

In [49]:
my_data[0,:]

array([  inf,   inf,   inf,  427.,  668.,  495.,  377.,  678.,   inf,
        177.,   inf,   inf,  870.,   inf,  869.,  624.,  300.,  609.,
        131.,   inf,  251.,   inf,   inf,   inf,  856.,  221.,  514.,
         inf,  591.,  762.,  182.,   56.,   inf,  884.,  412.,  273.,
        636.,   inf,   inf,  774.])

In [14]:
min(my_data[0, :])

56.0

In [15]:
np.argmin(my_data[0, :])

31

In [16]:
tree = [0]

In [17]:
len(tree)

1

In [18]:
my_data.shape

(40, 40)

In [21]:
my_data[0,1] = my_data[1,0] = 3

In [22]:
my_data

array([[   3.,    3.,   inf, ...,   inf,   inf,  774.],
       [   3.,   inf,  262., ...,  102.,  636.,  289.],
       [  inf,  262.,   inf, ...,  168.,  432.,  833.],
       ..., 
       [  inf,  102.,  168., ...,   inf,  371.,  680.],
       [  inf,  636.,  432., ...,  371.,   inf,  540.],
       [ 774.,  289.,  833., ...,  680.,  540.,   inf]])

In [30]:
np.amin(my_data[[0,3,5]])

3.0

In [32]:
my_data[[0,3,5]].argmin()

0

In [50]:
my_data[[0,31]]


array([[  inf,   inf,   inf,  427.,  668.,  495.,  377.,  678.,   inf,
         177.,   inf,   inf,  870.,   inf,  869.,  624.,  300.,  609.,
         131.,   inf,  251.,   inf,   inf,   inf,  856.,  221.,  514.,
          inf,  591.,  762.,  182.,   56.,   inf,  884.,  412.,  273.,
         636.,   inf,   inf,  774.],
       [  56.,   inf,  699.,  615.,  873.,   inf,  232.,  900.,  883.,
          inf,  772.,  675.,   inf,  227.,   inf,   68.,  196.,   inf,
         649.,  182.,  927.,  962.,   inf,   inf,  349.,  736.,   inf,
          inf,  505.,  349.,  965.,   inf,  474.,  178.,  833.,   inf,
          inf,  555.,  853.,   inf]])

In [55]:
np.amin(my_data[[0,31]])

68.0

In [53]:
my_data[0,31] = my_data[31, 0] = np.inf

In [56]:
my_data[[0]]

array([[  inf,   inf,   inf,  427.,  668.,  495.,  377.,  678.,   inf,
         177.,   inf,   inf,  870.,   inf,  869.,  624.,  300.,  609.,
         131.,   inf,  251.,   inf,   inf,   inf,  856.,  221.,  514.,
          inf,  591.,  762.,  182.,   inf,   inf,  884.,  412.,  273.,
         636.,   inf,   inf,  774.]])

In [57]:
my_data[[0,1], 1] = 0

In [58]:
my_data

array([[  inf,    0.,   inf, ...,   inf,   inf,  774.],
       [  inf,    0.,  262., ...,  102.,  636.,  289.],
       [  inf,  262.,   inf, ...,  168.,  432.,  833.],
       ..., 
       [  inf,  102.,  168., ...,   inf,  371.,  680.],
       [  inf,  636.,  432., ...,  371.,   inf,  540.],
       [ 774.,  289.,  833., ...,  680.,  540.,   inf]])

In [59]:
my_data[[0,1]]

array([[  inf,    0.,   inf,  427.,  668.,  495.,  377.,  678.,   inf,
         177.,   inf,   inf,  870.,   inf,  869.,  624.,  300.,  609.,
         131.,   inf,  251.,   inf,   inf,   inf,  856.,  221.,  514.,
          inf,  591.,  762.,  182.,   inf,   inf,  884.,  412.,  273.,
         636.,   inf,   inf,  774.],
       [  inf,    0.,  262.,   inf,   inf,  508.,  472.,  799.,   inf,
         956.,  578.,  363.,  940.,  143.,   inf,  162.,  122.,  910.,
          inf,  729.,  802.,  941.,  922.,  573.,  531.,  539.,  667.,
         607.,   inf,  920.,   inf,   inf,  315.,  649.,  937.,   inf,
         185.,  102.,  636.,  289.]])